name: mglyph-web

# ! WARNING: .env files have to be set up manually for pre-production purposes !

# Docker Compose configuration for Pre-Production environment
# this environment is meant to be as close as possible to production
# api - uses the production Dockerfile
# ui  - uses a special pre-production Dockerfile that builds the needed production static
#       files, but serves them with a `vite preview` server for testing purposes. This allows
#       testing the production build without needing a full web server setup
# db  - uses same configuration as development environment

services:

  api:
    depends_on:
      - db
    build: 
      context: ./api
      dockerfile: ./Prod.Dockerfile
    ports:
      - 8888:8888
    read_only: false

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  ui:
    build: 
      context: ./ui
      dockerfile: ./Pre-Prod.Dockerfile
    ports:
      - 8080:8080
      - 4173:4173
    read_only: false

volumes:
  db_data:

secrets:
  postgres_password:
    file: ./docker_config/postgres_password.secret
  postgres_user:
    file: ./docker_config/postgres_user.secret
  postgres_db:
    file: ./docker_config/postgres_db.secret
