name: mglyph-web

# ! WARNING: .env files have to be set up manually for production deployment !

# Docker Compose configuration for Production environment

services:

  api:
    container_name: api
    depends_on:
      - db
    build: 
      context: ./api
      dockerfile: ./Prod.Dockerfile
    ports:
      - 8888:8888
    read_only: false

  db:
    container_name: db
    image: postgres:18-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    ports:
      - 5432:5432
    volumes:
      - db_data_prod:/var/lib/postgresql/data

  ui:
    container_name: ui
    build: 
      context: ./ui
      dockerfile: ./Prod.Dockerfile
    ports:
      - 8080:80
      - 4173:4173
    read_only: false

volumes:
  db_data_prod:

secrets:
  postgres_password:
    file: ./docker_config/postgres_password_prod.secret
  postgres_user:
    file: ./docker_config/postgres_user_prod.secret
  postgres_db:
    file: ./docker_config/postgres_db_prod.secret
