"""add file table

Revision ID: a36fe8820b27
Revises: 8e296511a285
Create Date: 2026-03-31 19:54:29.054596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a36fe8820b27'
down_revision: Union[str, Sequence[str], None] = '8e296511a285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('path')
    )

    op.add_column('malleable_glyph', sa.Column('zip_file_id', sa.Uuid(), nullable=False))
    op.create_foreign_key('fk_malleable_glyph_zip_file_id', 'malleable_glyph', 'file', ['zip_file_id'], ['id'])
    op.drop_column('malleable_glyph', 'zip_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('malleable_glyph', sa.Column('zip_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('fk_malleable_glyph_zip_file_id', 'malleable_glyph', type_='foreignkey')
    op.drop_column('malleable_glyph', 'zip_file_id')
    op.drop_table('file')
    # ### end Alembic commands ###
