"""new_malleable_glyph_table

Revision ID: 8cc2bdbf802f
Revises: 6ec0ae89971a
Create Date: 2026-02-16 18:47:31.362901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8cc2bdbf802f'
down_revision: Union[str, Sequence[str], None] = '6ec0ae89971a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('malleable_glyph',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('long_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('last_updated_time', sa.DateTime(), nullable=False),
        sa.Column('submission_time', sa.DateTime(), nullable=True),
        sa.Column('zip_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_code_public', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('creator_id', sa.Uuid(), nullable=False),
        
        sa.ForeignKeyConstraint(['creator_id'], ['end_user.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_malleable_glyph_creator_id'), 'malleable_glyph', ['creator_id'], unique=False)
    op.create_index(op.f('ix_malleable_glyph_long_name'), 'malleable_glyph', ['long_name'], unique=False)
    op.create_index(op.f('ix_malleable_glyph_short_name'), 'malleable_glyph', ['short_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_malleable_glyph_short_name'), table_name='malleable_glyph')
    op.drop_index(op.f('ix_malleable_glyph_long_name'), table_name='malleable_glyph')
    op.drop_index(op.f('ix_malleable_glyph_creator_id'), table_name='malleable_glyph')
    op.drop_table('malleable_glyph')
    # ### end Alembic commands ###
