"""new_end_user_table

Revision ID: 2c2df5cff782
Revises: 7691a9df41cc
Create Date: 2026-02-12 00:18:10.364853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2c2df5cff782'
down_revision: Union[str, Sequence[str], None] = '7691a9df41cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('end_user',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='user'),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('google_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('count', sa.Integer(), nullable=False, server_default='0'),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_end_user_email'), 'end_user', ['email'], unique=True)
    op.create_index(op.f('ix_end_user_google_sub'), 'end_user', ['google_sub'], unique=True)
    op.create_index(op.f('ix_end_user_username'), 'end_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_end_user_username'), table_name='end_user')
    op.drop_index(op.f('ix_end_user_google_sub'), table_name='end_user')
    op.drop_index(op.f('ix_end_user_email'), table_name='end_user')
    op.drop_table('end_user')
    # ### end Alembic commands ###
