"""new_challenge_evaluator_link_table

Revision ID: 6929439eceac
Revises: b6007e88cad5
Create Date: 2026-02-15 03:19:05.255725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6929439eceac'
down_revision: Union[str, Sequence[str], None] = 'b6007e88cad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_evaluator',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('challenge_id', sa.Uuid(), nullable=False),
        sa.Column('evaluator_id', sa.Uuid(), nullable=False),

        sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id']),
        sa.ForeignKeyConstraint(['evaluator_id'], ['end_user.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('challenge_id', 'evaluator_id', name='uq_challenge_evaluator')
    )
    op.create_index(op.f('ix_challenge_evaluator_challenge_id'), 'challenge_evaluator', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_evaluator_evaluator_id'), 'challenge_evaluator', ['evaluator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_evaluator_evaluator_id'), table_name='challenge_evaluator')
    op.drop_index(op.f('ix_challenge_evaluator_challenge_id'), table_name='challenge_evaluator')
    op.drop_table('challenge_evaluator')
    # ### end Alembic commands ###
