"""drop_hero_table_and_count_col_in_user

Revision ID: cf496fe2090a
Revises: 7f19232fb521
Create Date: 2026-04-27 10:42:47.444451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cf496fe2090a'
down_revision: Union[str, Sequence[str], None] = '7f19232fb521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hero_age'), table_name='hero')
    op.drop_index(op.f('ix_hero_name'), table_name='hero')
    op.drop_table('hero')
    op.drop_column('end_user', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('end_user', sa.Column('count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_table('hero',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('hero_pkey'))
    )
    op.create_index(op.f('ix_hero_name'), 'hero', ['name'], unique=False)
    op.create_index(op.f('ix_hero_age'), 'hero', ['age'], unique=False)
    # ### end Alembic commands ###
