"""add_state_column_to_challenge_evaluator

Revision ID: ab7278e27a86
Revises: fbb1b05e7534
Create Date: 2026-02-24 19:38:03.963006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ab7278e27a86'
down_revision: Union[str, Sequence[str], None] = 'fbb1b05e7534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_evaluator', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge_evaluator', 'state')
    # ### end Alembic commands ###
