"""new_mglyph_evaluator_table

Revision ID: 721181e636cb
Revises: bd7703cccd0f
Create Date: 2026-02-17 00:28:52.978618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '721181e636cb'
down_revision: Union[str, Sequence[str], None] = 'bd7703cccd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mglyph_evaluator',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('mglyph_evaluation_id', sa.Uuid(), nullable=False),
        sa.Column('challenge_evaluator_id', sa.Uuid(), nullable=False),
        
        sa.ForeignKeyConstraint(['challenge_evaluator_id'], ['challenge_evaluator.id']),
        sa.ForeignKeyConstraint(['mglyph_evaluation_id'], ['mglyph_evaluation.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('mglyph_evaluation_id', 'challenge_evaluator_id', name='uq_challenge_mglyph_evaluator')
    )
    op.create_index(op.f('ix_mglyph_evaluator_challenge_evaluator_id'), 'mglyph_evaluator', ['challenge_evaluator_id'], unique=False)
    op.create_index(op.f('ix_mglyph_evaluator_mglyph_evaluation_id'), 'mglyph_evaluator', ['mglyph_evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mglyph_evaluator_mglyph_evaluation_id'), table_name='mglyph_evaluator')
    op.drop_index(op.f('ix_mglyph_evaluator_challenge_evaluator_id'), table_name='mglyph_evaluator')
    op.drop_table('mglyph_evaluator')
    # ### end Alembic commands ###
