"""use_and_create_enum_types

Revision ID: 1f34b1e9c694
Revises: ab7278e27a86
Create Date: 2026-02-25 01:34:51.327000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1f34b1e9c694'
down_revision: Union[str, Sequence[str], None] = 'ab7278e27a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('same', 'different', name='rotationtype').create(op.get_bind())
    sa.Enum('greater', 'less', 'equal', name='answeredsymbol').create(op.get_bind())
    sa.Enum('user', 'admin', name='userrole').create(op.get_bind())
    sa.Enum('open', 'closed', name='mglyphflagstatus').create(op.get_bind())
    sa.Enum('other', name='mglyphflagtype').create(op.get_bind())
    sa.Enum('volunteer_pending', 'volunteer_rejected', 'confirmed', 'invited_pending', 'invited_rejected', name='challengeevaluatorstate').create(op.get_bind())
    op.alter_column('answer', 'answered_symbol',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.Enum('greater', 'less', 'equal', name='answeredsymbol'),
               existing_nullable=False,
               postgresql_using='answered_symbol::answeredsymbol')
    op.alter_column('answer', 'rotation_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('same', 'different', name='rotationtype'),
               existing_nullable=True,
               postgresql_using='rotation_type::rotationtype')
    op.alter_column('challenge_evaluator', 'state',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('volunteer_pending', 'volunteer_rejected', 'confirmed', 'invited_pending', 'invited_rejected', name='challengeevaluatorstate'),
               existing_nullable=False,
               postgresql_using='state::challengeevaluatorstate')
    
    # drop server default for 'role' column before altering it, because changing the type of a column with a server default that is not compatible with the new type can cause issues in some databases (e.g. PostgreSQL)
    op.alter_column('end_user', 'role',
               existing_type=sa.VARCHAR(),
               existing_nullable=False,
               server_default=None)
    
    op.alter_column('end_user', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('user', 'admin', name='userrole'),
               existing_nullable=False,
               server_default='user',
               postgresql_using='role::userrole')
    op.alter_column('mglyph_report_flag', 'flag_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('other', name='mglyphflagtype'),
               existing_nullable=False,
               postgresql_using='flag_type::mglyphflagtype')
    op.alter_column('mglyph_report_flag', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('open', 'closed', name='mglyphflagstatus'),
               existing_nullable=False,
               server_default='open',
               postgresql_using='status::mglyphflagstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mglyph_report_flag', 'status',
               existing_type=sa.Enum('open', 'closed', name='mglyphflagstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               server_default=None)
    op.alter_column('mglyph_report_flag', 'flag_type',
               existing_type=sa.Enum('other', name='mglyphflagtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('end_user', 'role',
               existing_type=sa.Enum('user', 'admin', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               server_default=sa.text("'user'::character varying"))
    op.alter_column('challenge_evaluator', 'state',
               existing_type=sa.Enum('volunteer_pending', 'volunteer_rejected', 'confirmed', 'invited_pending', 'invited_rejected', name='challengeevaluatorstate'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('answer', 'rotation_type',
               existing_type=sa.Enum('same', 'different', name='rotationtype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('answer', 'answered_symbol',
               existing_type=sa.Enum('greater', 'less', 'equal', name='answeredsymbol'),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
    sa.Enum('volunteer_pending', 'volunteer_rejected', 'confirmed', 'invited_pending', 'invited_rejected', name='challengeevaluatorstate').drop(op.get_bind())
    sa.Enum('other', name='mglyphflagtype').drop(op.get_bind())
    sa.Enum('open', 'closed', name='mglyphflagstatus').drop(op.get_bind())
    sa.Enum('user', 'admin', name='userrole').drop(op.get_bind())
    sa.Enum('greater', 'less', 'equal', name='answeredsymbol').drop(op.get_bind())
    sa.Enum('same', 'different', name='rotationtype').drop(op.get_bind())
    # ### end Alembic commands ###
