"""challenge_evaluator_uses_state_and_type_enum

Revision ID: 7f19232fb521
Revises: a36fe8820b27
Create Date: 2026-04-13 15:37:59.920011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7f19232fb521'
down_revision: Union[str, Sequence[str], None] = 'a36fe8820b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('volunteer', 'invited', name='invitationtype').create(op.get_bind())
    sa.Enum('pending', 'rejected', 'confirmed', name='invitationstate').create(op.get_bind())
    op.add_column('challenge_evaluator', sa.Column('invitation_state', postgresql.ENUM('pending', 'rejected', 'confirmed', name='invitationstate', create_type=False), nullable=False))
    op.add_column('challenge_evaluator', sa.Column('invitation_type', postgresql.ENUM('volunteer', 'invited', name='invitationtype', create_type=False), nullable=False))
    op.drop_column('challenge_evaluator', 'state')
    sa.Enum('volunteer_pending', 'volunteer_rejected', 'confirmed', 'invited_pending', 'invited_rejected', name='challengeevaluatorstate').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('volunteer_pending', 'volunteer_rejected', 'confirmed', 'invited_pending', 'invited_rejected', name='challengeevaluatorstate').create(op.get_bind())
    op.add_column('challenge_evaluator', sa.Column('state', postgresql.ENUM('volunteer_pending', 'volunteer_rejected', 'confirmed', 'invited_pending', 'invited_rejected', name='challengeevaluatorstate', create_type=False), autoincrement=False, nullable=False))
    op.drop_column('challenge_evaluator', 'invitation_type')
    op.drop_column('challenge_evaluator', 'invitation_state')
    sa.Enum('pending', 'rejected', 'confirmed', name='invitationstate').drop(op.get_bind())
    sa.Enum('volunteer', 'invited', name='invitationtype').drop(op.get_bind())
    # ### end Alembic commands ###
