"""answer_table_timezone_aware

Revision ID: f06358cf5083
Revises: dbd35a8ccea1
Create Date: 2026-02-23 21:13:42.301475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f06358cf5083'
down_revision: Union[str, Sequence[str], None] = 'dbd35a8ccea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Alter the "answer" table (timezone aware)
    op.alter_column('answer', 'answer_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.func.now())
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Alter the "answer" table (remove timezone awareness)
    op.alter_column('answer', 'answer_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    
    # ### end Alembic commands ###
