"""add_creation_time_column_to_end_user

Revision ID: fbb1b05e7534
Revises: f06358cf5083
Create Date: 2026-02-23 21:17:50.344369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fbb1b05e7534'
down_revision: Union[str, Sequence[str], None] = 'f06358cf5083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add "creation_time" column to "end_user" table
    op.add_column('end_user', sa.Column('creation_time', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove "creation_time" column from "end_user" table
    op.drop_column('end_user', 'creation_time')

    # ### end Alembic commands ###
