"""new_answer_table

Revision ID: a57a7785257c
Revises: 721181e636cb
Create Date: 2026-02-17 00:59:07.890485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a57a7785257c'
down_revision: Union[str, Sequence[str], None] = '721181e636cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('first_glyph_value', sa.Float(), nullable=False),
        sa.Column('second_glyph_value', sa.Float(), nullable=False),
        sa.Column('answered_symbol', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
        sa.Column('is_answer_correct', sa.Boolean(), nullable=False),
        sa.Column('glyph_distance', sa.Float(), nullable=False),
        sa.Column('answer_time', sa.DateTime(), nullable=False),
        sa.Column('time_taken', sa.Interval(), nullable=False),
        sa.Column('rotation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('first_glyph_rotation_angle', sa.Float(), nullable=False),
        sa.Column('second_glyph_rotation_angle', sa.Float(), nullable=False),
        sa.Column('mglyph_evaluator_id', sa.Uuid(), nullable=False),
        
        sa.ForeignKeyConstraint(['mglyph_evaluator_id'], ['mglyph_evaluator.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_mglyph_evaluator_id'), 'answer', ['mglyph_evaluator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_mglyph_evaluator_id'), table_name='answer')
    op.drop_table('answer')
    # ### end Alembic commands ###
