"""add_mglyph_reportflag_relationship

Revision ID: 8e296511a285
Revises: 1f34b1e9c694
Create Date: 2026-03-06 21:23:48.670583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8e296511a285'
down_revision: Union[str, Sequence[str], None] = '1f34b1e9c694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mglyph_report_flag', sa.Column('mglyph_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_mglyph_report_flag_mglyph_id'), 'mglyph_report_flag', ['mglyph_id'], unique=False)
    op.create_foreign_key(None, 'mglyph_report_flag', 'malleable_glyph', ['mglyph_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mglyph_report_flag', type_='foreignkey')
    op.drop_index(op.f('ix_mglyph_report_flag_mglyph_id'), table_name='mglyph_report_flag')
    op.drop_column('mglyph_report_flag', 'mglyph_id')
    # ### end Alembic commands ###
