"""new_mglyph_report_flag_table

Revision ID: ddfaa7400a51
Revises: a57a7785257c
Create Date: 2026-02-17 01:29:26.924551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ddfaa7400a51'
down_revision: Union[str, Sequence[str], None] = 'a57a7785257c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mglyph_report_flag',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('flag_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('creation_time', sa.DateTime(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('last_updated_time', sa.DateTime(), nullable=False),
        sa.Column('history', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('user_reporter_id', sa.Uuid(), nullable=False),
        sa.Column('user_resolver_id', sa.Uuid(), nullable=True),

        sa.ForeignKeyConstraint(['user_reporter_id'], ['end_user.id']),
        sa.ForeignKeyConstraint(['user_resolver_id'], ['end_user.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mglyph_report_flag')
    # ### end Alembic commands ###
