"""add_creator_column_to_challenge_table

Revision ID: ce446c24d488
Revises: ddfaa7400a51
Create Date: 2026-02-20 19:13:35.615699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ce446c24d488'
down_revision: Union[str, Sequence[str], None] = 'ddfaa7400a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.create_foreign_key('fk_challenge_creator_id_end_user_id', 'challenge', 'end_user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_challenge_creator_id_end_user_id', 'challenge', type_='foreignkey')
    op.drop_column('challenge', 'creator_id')
    # ### end Alembic commands ###
