"""new_challenge_table_and_relation_to_end_user

Revision ID: b6007e88cad5
Revises: 2c2df5cff782
Create Date: 2026-02-12 02:02:45.628173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b6007e88cad5'
down_revision: Union[str, Sequence[str], None] = '2c2df5cff782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # create challenge table
    op.create_table('challenge',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('creation_time', sa.DateTime(), nullable=False),
        sa.Column('glyph_submit_deadline', sa.DateTime(), nullable=False),
        sa.Column('submissions_ended', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('challenge_finished', sa.Boolean(), nullable=False, server_default=sa.false()),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_challenge_name'), 'challenge', ['name'], unique=True)

    # create challenge_solver table
    op.create_table('challenge_solver',
        sa.Column('challenge_id', sa.Uuid(), nullable=False),
        sa.Column('solver_id', sa.Uuid(), nullable=False),

        sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id']),
        sa.ForeignKeyConstraint(['solver_id'], ['end_user.id']),
        sa.PrimaryKeyConstraint('challenge_id', 'solver_id')
    )
    op.create_index(op.f('ix_challenge_solver_challenge_id'), 'challenge_solver', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_solver_solver_id'), 'challenge_solver', ['solver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_solver_solver_id'), table_name='challenge_solver')
    op.drop_index(op.f('ix_challenge_solver_challenge_id'), table_name='challenge_solver')
    op.drop_table('challenge_solver')
    
    op.drop_index(op.f('ix_challenge_name'), table_name='challenge')
    op.drop_table('challenge')
    # ### end Alembic commands ###
