server {
    listen 80;
    # access_log off; # Disable access logs in production
    gzip on; # Enable compression
    gzip_types text/css application/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # Support Vue Router history mode

        # Security headers
        # add_header X-Frame-Options "DENY";
        # add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'";
        # add_header Strict-Transport-Security "max-age=63072000" always;
    }

    # Block sensitive files
    location ~ /\.(?!well-known).* {
        deny all;
    }
}